// Tyra Decor - Product catalogue seed data (from official PDF)
// All prices are in INR, exclusive of GST

export const CATEGORIES = [
  { slug: 'chairs', name: 'Chairs' },
  { slug: 'tables', name: 'Tables' },
  { slug: 'planters', name: 'Planters' },
  { slug: 'suites', name: 'Suites' },
];

const chairImg1 = 'https://images.unsplash.com/photo-1611140295826-ec6b41e392c9?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200';
const chairImg2 = 'https://images.unsplash.com/photo-1554390536-ae13a0fcdba2?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200';
const chairImg3 = 'https://images.unsplash.com/photo-1648143347807-6b25a5498d42?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200';
const chairImg4 = 'https://images.unsplash.com/photo-1650752973682-5fe15526cb64?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200';
const tableImg1 = 'https://images.unsplash.com/photo-1708994021081-ba6825eaae89?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200';
const tableImg2 = 'https://images.unsplash.com/photo-1657740037571-e0347224483f?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200';
const tableImg3 = 'https://images.unsplash.com/photo-1578112010316-b44c50d27b2b?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200';
const planterImg1 = 'https://images.unsplash.com/photo-1582142870523-7249388696f4?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200';
const planterImg2 = 'https://images.unsplash.com/photo-1582142841029-5a095866c1e0?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200';
const suiteImg = 'https://images.unsplash.com/photo-1599696848652-f0ff23bc911f?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200';

export const SEED_PRODUCTS = [
  // ================= CHAIRS =================
  {
    sku: 'TD-CH-HALO',
    name: 'The Halo Armchair',
    category: 'chairs',
    tagline: 'The high-back lounge seat',
    description: 'Dramatic circular armrests and an elevated backrest give the Halo its signature silhouette. An ergonomic curve and cushioned seat make it a luxurious statement piece — built on a weather-resistant rubber frame with a high-gloss finish.',
    dimensions: '100 (H) x 45 (Seat) x 66 (Base) cm',
    material: 'Handwoven Recycled Rubber',
    colors: ['Charcoal Black'],
    price: 4500,
    originalPrice: 6000,
    image: chairImg1,
    featured: true,
    availability: 'In Stock',
    note: 'Cushion sold separately',
  },
  {
    sku: 'TD-CH-COTL',
    name: 'The Cottage Chair — Large',
    category: 'chairs',
    tagline: 'Classic silhouette, industrial edge',
    description: 'An intricate basket-weave seat on a reinforced lattice base. Durable enough for high-traffic use and the outdoors, refined enough for interiors.',
    dimensions: '87 (H) x 45 (Seat) x 63 (Base) cm',
    material: 'Handwoven Recycled Rubber',
    colors: ['Charcoal Black'],
    price: 4160,
    originalPrice: 5550,
    image: chairImg2,
    featured: false,
    availability: 'In Stock',
    note: 'Cushion sold separately',
  },
  {
    sku: 'TD-CH-COTS',
    name: 'The Cottage Chair — Small',
    category: 'chairs',
    tagline: 'Compact basket-weave classic',
    description: 'The compact edition of the Cottage — same basket weave, reinforced base and outdoor-ready durability in a smaller footprint.',
    dimensions: '71 (H) x 39 (Seat) x 51 (Base) cm',
    material: 'Handwoven Recycled Rubber',
    colors: ['Charcoal Black'],
    price: 3375,
    originalPrice: 4500,
    image: chairImg2,
    featured: false,
    availability: 'In Stock',
    note: 'Cushion sold separately',
  },
  {
    sku: 'TD-CH-LOWR',
    name: 'The Low Rider',
    category: 'chairs',
    tagline: 'The deep-seated lounge',
    description: 'Deep-set with a natural sink-in curve. Waterproof, UV-resistant and equally at home on a terrace, garden corner or indoor lounge.',
    dimensions: '54 (H) x 24 (Seat) x 61 (Base) cm',
    material: 'Handwoven Recycled Rubber',
    colors: ['Charcoal Black'],
    price: 3150,
    originalPrice: 4200,
    image: chairImg3,
    featured: true,
    availability: 'In Stock',
    note: 'Cushion sold separately',
  },
  {
    sku: 'TD-CH-SLNT',
    name: 'The Slant Stool',
    category: 'chairs',
    tagline: 'The ergonomic low seat',
    description: 'A unique angled weave encourages a naturally reclined posture with lower-back support. Doubles as a footrest or floor-level social seat.',
    dimensions: '45 (H) x 45 (Seat) x 63 (Base) cm',
    material: 'Handwoven Recycled Rubber',
    colors: ['Charcoal Black'],
    price: 2400,
    originalPrice: 3200,
    image: chairImg4,
    featured: false,
    availability: 'In Stock',
    note: 'Cushion sold separately',
  },

  // ================= TABLES =================
  {
    sku: 'TD-TB-HUBL',
    name: 'The Hub Table — Large',
    category: 'tables',
    tagline: 'The versatile dining centre',
    description: 'A spacious hand-woven top and matching lower storage shelf on a weighted circular frame. Heat-resistant with a high-gloss finish.',
    dimensions: '82 (H) x 122 (Top) x 41 (Base) cm',
    material: 'Handwoven Recycled Rubber',
    colors: ['Charcoal Black'],
    price: 10500,
    originalPrice: 14000,
    image: tableImg1,
    featured: true,
    availability: 'In Stock',
  },
  {
    sku: 'TD-TB-HUBS',
    name: 'The Hub Table — Small',
    category: 'tables',
    tagline: 'The versatile dining centre',
    description: 'Compact companion to the Hub Large — same weave, weighted circular frame and lower storage shelf.',
    dimensions: '79 (H) x 92 (Top) x 36 (Base) cm',
    material: 'Handwoven Recycled Rubber',
    colors: ['Charcoal Black'],
    price: 9375,
    originalPrice: 12500,
    image: tableImg1,
    featured: false,
    availability: 'In Stock',
  },
  {
    sku: 'TD-TB-MUSH',
    name: 'The Mushroom Table',
    category: 'tables',
    tagline: 'The sculptural accent piece',
    description: 'A unique bulbous silhouette with a hand-woven circular top on a sturdy weighted base. Compact, weather-proof, unmistakably Tyra.',
    dimensions: '55 (H) x 75 (Top) x 62 (Base) cm',
    material: 'Handwoven Recycled Rubber',
    colors: ['Charcoal Black'],
    price: 3750,
    originalPrice: 5000,
    image: tableImg2,
    featured: true,
    availability: 'In Stock',
  },
  {
    sku: 'TD-TB-CORE',
    name: 'The Core Table',
    category: 'tables',
    tagline: 'The heavy-duty centrepiece',
    description: 'A solid, weighted coffee table with a flat-top weave and heat-proof high-gloss finish. Zero maintenance — stands up to rain and sun.',
    dimensions: '43 (H) x 64 (Top) x 62 (Base) cm',
    material: 'Handwoven Recycled Rubber',
    colors: ['Charcoal Black'],
    price: 4125,
    originalPrice: 5500,
    image: tableImg3,
    featured: false,
    availability: 'In Stock',
  },

  // ================= PLANTERS =================
  {
    sku: 'TD-PL-ESTATE',
    name: 'The Estate Planter',
    category: 'planters',
    tagline: 'Anchor your landscape',
    description: 'Our largest, most robust planter (30 inches tall) — designed to support trees and heavy root systems on a reinforced weighted base.',
    dimensions: '76 (H) x 48 (Mouth) x 105 (Planter W) cm',
    material: 'Handwoven Recycled Rubber',
    colors: ['Charcoal Black'],
    price: 9200,
    originalPrice: 11500,
    image: planterImg1,
    featured: true,
    availability: 'In Stock',
    note: 'Handles sold separately',
  },
  {
    sku: 'TD-PL-PIL24',
    name: 'Pillar Planter — 24"',
    category: 'planters',
    tagline: 'Vertical statement planter',
    description: 'For high-visibility corners and heavy foliage — tall, architectural, unmistakably industrial-luxe.',
    dimensions: '61 (H) x 48 (Mouth) x 105 (W) cm',
    material: 'Handwoven Recycled Rubber',
    colors: ['Charcoal Black'],
    price: 1280,
    originalPrice: 1600,
    image: planterImg2,
    featured: false,
    availability: 'In Stock',
    note: 'Handles sold separately',
  },
  {
    sku: 'TD-PL-PIL20',
    name: 'Pillar Planter — 20"',
    category: 'planters',
    tagline: 'Mid-size vertical accent',
    description: 'Ideal for doorways, garden paths and mid-height plants that deserve a strong architectural pedestal.',
    dimensions: '50 (H) x 30 (Mouth) x 38 (W) cm',
    material: 'Handwoven Recycled Rubber',
    colors: ['Charcoal Black'],
    price: 1120,
    originalPrice: 1400,
    image: planterImg2,
    featured: false,
    availability: 'In Stock',
    note: 'Handles sold separately',
  },
  {
    sku: 'TD-PL-CRT18',
    name: 'Courtyard Planter — 18"',
    category: 'planters',
    tagline: 'Everyday elegance for patios',
    description: 'Versatile and easy to move — a mid-size planter for patios, foyers and open-plan spaces.',
    dimensions: '45 (H) x 40 (Mouth) x 40 (W) cm',
    material: 'Handwoven Recycled Rubber',
    colors: ['Charcoal Black'],
    price: 1000,
    originalPrice: 1250,
    image: planterImg1,
    featured: false,
    availability: 'In Stock',
    note: 'Handles sold separately',
  },
  {
    sku: 'TD-PL-CRT16',
    name: 'Courtyard Planter — 16"',
    category: 'planters',
    tagline: 'Compact & deep',
    description: 'Compact yet deep — perfect for balconies, indoor greenery and lush floral arrangements.',
    dimensions: '40 (H) x 40 (Mouth) x 40 (W) cm',
    material: 'Handwoven Recycled Rubber',
    colors: ['Charcoal Black'],
    price: 900,
    originalPrice: 1125,
    image: planterImg1,
    featured: false,
    availability: 'In Stock',
    note: 'Handles sold separately',
  },
  {
    sku: 'TD-PL-MK15',
    name: 'Matka Planter — 15"',
    category: 'planters',
    tagline: 'Inspired by earthenware',
    description: 'A smooth, wide-rimmed profile designed for substantial soil volume — for statement shrubs and indoor plants.',
    dimensions: '38 (H) x 38 (Mouth) x 50 (W) cm',
    material: 'Handwoven Recycled Rubber',
    colors: ['Charcoal Black'],
    price: 950,
    originalPrice: 1200,
    image: planterImg2,
    featured: false,
    availability: 'In Stock',
  },
  {
    sku: 'TD-PL-MK14',
    name: 'Matka Planter — 14"',
    category: 'planters',
    tagline: 'Mid-size earthenware form',
    description: 'Best for doorways and garden corners — the classic Matka silhouette in a mid-size profile.',
    dimensions: '35 (H) x 38 (Mouth) x 50 (W) cm',
    material: 'Handwoven Recycled Rubber',
    colors: ['Charcoal Black'],
    price: 900,
    originalPrice: 1150,
    image: planterImg2,
    featured: false,
    availability: 'In Stock',
  },
  {
    sku: 'TD-PL-MK12',
    name: 'Matka Planter — 12"',
    category: 'planters',
    tagline: 'Compact patio accent',
    description: 'A compact Matka for low-level patio accents and clustered arrangements.',
    dimensions: '30 (H) x 38 (Mouth) x 50 (W) cm',
    material: 'Handwoven Recycled Rubber',
    colors: ['Charcoal Black'],
    price: 850,
    originalPrice: 1000,
    image: planterImg2,
    featured: false,
    availability: 'In Stock',
  },
  {
    sku: 'TD-PL-BL9',
    name: 'Bloom Pot — 9"',
    category: 'planters',
    tagline: 'Windowsill greenery',
    description: 'Lightweight yet durable, ideal for larger windowsills and side tables.',
    dimensions: '23 (H) x 33 (Mouth) x 33 (W) cm',
    material: 'Handwoven Recycled Rubber',
    colors: ['Charcoal Black'],
    price: 550,
    originalPrice: 700,
    image: planterImg1,
    featured: false,
    availability: 'In Stock',
  },
  {
    sku: 'TD-PL-BL6',
    name: 'Bloom Pot — 6"',
    category: 'planters',
    tagline: 'Desktop greenery',
    description: 'A desktop-friendly bloom pot — perfect for tiered garden displays.',
    dimensions: '15 (H) x 33 (Mouth) x 33 (W) cm',
    material: 'Handwoven Recycled Rubber',
    colors: ['Charcoal Black'],
    price: 400,
    originalPrice: 500,
    image: planterImg1,
    featured: false,
    availability: 'In Stock',
  },
  {
    sku: 'TD-PL-BL5',
    name: 'Bloom Pot — 5"',
    category: 'planters',
    tagline: 'The tiniest accent',
    description: 'Our most compact planter — for small-space accents and low-maintenance succulents.',
    dimensions: '13 (H) x 20 (Mouth) x 20 (W) cm',
    material: 'Handwoven Recycled Rubber',
    colors: ['Charcoal Black'],
    price: 350,
    originalPrice: 450,
    image: planterImg1,
    featured: false,
    availability: 'In Stock',
  },

  // ================= SUITES =================
  { sku: 'TD-SU-SOV', name: 'The Sovereign Suite', category: 'suites', tagline: '1 Large Hub Table + 4 Halo Armchairs', description: 'The flagship set — a Large Hub Table anchored by four Halo Armchairs. A statement of executive luxury.', dimensions: '4-Chair Set', material: 'Handwoven Recycled Rubber', colors: ['Charcoal Black'], price: 26600, originalPrice: 38000, image: suiteImg, featured: true, availability: 'Made to Order' },
  { sku: 'TD-SU-EXE', name: 'The Executive', category: 'suites', tagline: '1 Large Hub Table + 2 Halo Armchairs', description: 'A more intimate configuration of the flagship — same Hub Table, two Halo Armchairs.', dimensions: '2-Chair Set', material: 'Handwoven Recycled Rubber', colors: ['Charcoal Black'], price: 18200, originalPrice: 26000, image: suiteImg, featured: false, availability: 'Made to Order' },
  { sku: 'TD-SU-GHUB', name: 'The Grand Hub', category: 'suites', tagline: '1 Large Hub Table + 4 Cottage Chairs (L)', description: 'A grand-scale dining set on the Large Hub Table with four Large Cottage Chairs.', dimensions: '4-Chair Set', material: 'Handwoven Recycled Rubber', colors: ['Charcoal Black'], price: 25340, originalPrice: 36200, image: suiteImg, featured: true, availability: 'Made to Order' },
  { sku: 'TD-SU-SKY', name: 'The Skyline', category: 'suites', tagline: '1 Hub Table + 2 Cottage Chairs (L)', description: 'Two Cottage Chairs paired with a Hub Table — clean, statuesque, timeless.', dimensions: '2-Chair Set', material: 'Handwoven Recycled Rubber', colors: ['Charcoal Black'], price: 17500, originalPrice: 25100, image: suiteImg, featured: false, availability: 'Made to Order' },
  { sku: 'TD-SU-PSQ', name: 'The Patio Square', category: 'suites', tagline: '1 Core Table + 4 Small Cottage Chairs', description: 'A weather-ready four-seater patio set built on the Core Table.', dimensions: '4-Chair Set', material: 'Handwoven Recycled Rubber', colors: ['Charcoal Black'], price: 16450, originalPrice: 23500, image: suiteImg, featured: false, availability: 'Made to Order' },
  { sku: 'TD-SU-GRD', name: 'The Garden', category: 'suites', tagline: '1 Core Table + 2 Small Cottage Chairs', description: 'A two-seater retreat built for gardens and balconies.', dimensions: '2-Chair Set', material: 'Handwoven Recycled Rubber', colors: ['Charcoal Black'], price: 10100, originalPrice: 14500, image: suiteImg, featured: false, availability: 'Made to Order' },
  { sku: 'TD-SU-TN', name: 'The Terrace Nook', category: 'suites', tagline: '1 Mushroom Table + 4 Small Cottage Chairs', description: 'A sculptural four-seater with the Mushroom Table at its centre.', dimensions: '4-Chair Set', material: 'Handwoven Recycled Rubber', colors: ['Charcoal Black'], price: 16100, originalPrice: 23000, image: suiteImg, featured: false, availability: 'Made to Order' },
  { sku: 'TD-SU-CAFE', name: 'The Cafe', category: 'suites', tagline: '1 Mushroom Table + 2 Small Cottage Chairs', description: 'A café-inspired two-seater set — perfect for tight balconies.', dimensions: '2-Chair Set', material: 'Handwoven Recycled Rubber', colors: ['Charcoal Black'], price: 9800, originalPrice: 14000, image: suiteImg, featured: false, availability: 'Made to Order' },
  { sku: 'TD-SU-SOC', name: 'The Social Circle', category: 'suites', tagline: '1 Core Table + 4 Low Riders', description: 'Deep-seated lounging around a Core Table — designed for long evenings.', dimensions: '4-Chair Set', material: 'Handwoven Recycled Rubber', colors: ['Charcoal Black'], price: 15610, originalPrice: 22300, image: suiteImg, featured: false, availability: 'Made to Order' },
  { sku: 'TD-SU-SUN', name: 'The Sunset', category: 'suites', tagline: '1 Core Table + 2 Low Riders', description: 'An intimate low-slung two-seater for sunset moments.', dimensions: '2-Chair Set', material: 'Handwoven Recycled Rubber', colors: ['Charcoal Black'], price: 9700, originalPrice: 13900, image: suiteImg, featured: false, availability: 'Made to Order' },
  { sku: 'TD-SU-ORB', name: 'The Orbit Group', category: 'suites', tagline: '1 Mushroom Table + 4 Low Riders', description: 'A sculptural configuration for social terraces.', dimensions: '4-Chair Set', material: 'Handwoven Recycled Rubber', colors: ['Charcoal Black'], price: 15260, originalPrice: 21800, image: suiteImg, featured: false, availability: 'Made to Order' },
  { sku: 'TD-SU-LR', name: 'The Low Retreat', category: 'suites', tagline: '1 Mushroom Table + 2 Low Riders', description: 'A relaxed pairing for private corners.', dimensions: '2-Chair Set', material: 'Handwoven Recycled Rubber', colors: ['Charcoal Black'], price: 9380, originalPrice: 13400, image: suiteImg, featured: false, availability: 'Made to Order' },
  { sku: 'TD-SU-RCL', name: 'The Recline Suite', category: 'suites', tagline: '1 Core Table + 4 Slant Stools', description: 'Ergonomic floor-level lounging with the Core Table at the centre.', dimensions: '4-Stool Set', material: 'Handwoven Recycled Rubber', colors: ['Charcoal Black'], price: 12810, originalPrice: 18300, image: suiteImg, featured: false, availability: 'Made to Order' },
  { sku: 'TD-SU-STR', name: 'The Structure', category: 'suites', tagline: '1 Core Table + 2 Slant Stools', description: 'A compact ergonomic two-stool set.', dimensions: '2-Stool Set', material: 'Handwoven Recycled Rubber', colors: ['Charcoal Black'], price: 8300, originalPrice: 11900, image: suiteImg, featured: false, availability: 'Made to Order' },
  { sku: 'TD-SU-ACC', name: 'The Accent Group', category: 'suites', tagline: '1 Mushroom Table + 4 Slant Stools', description: 'A sculptural four-stool statement.', dimensions: '4-Stool Set', material: 'Handwoven Recycled Rubber', colors: ['Charcoal Black'], price: 12460, originalPrice: 17800, image: suiteImg, featured: false, availability: 'Made to Order' },
  { sku: 'TD-SU-CTR', name: 'The Contour', category: 'suites', tagline: '1 Mushroom Table + 2 Slant Stools', description: 'A compact, sculptural pairing.', dimensions: '2-Stool Set', material: 'Handwoven Recycled Rubber', colors: ['Charcoal Black'], price: 7900, originalPrice: 11400, image: suiteImg, featured: false, availability: 'Made to Order' },
];

export const COMPANY = {
  name: 'Tyra Décor',
  tagline: 'Recycled. Refined. Remarkable.',
  parent: 'A Brand by R.B. Tubes Pvt. Ltd.',
  phone1: '+91 77040 07055',
  phone2: '+91 63079 94948',
  email: 'tyra.decor@gmail.com',
  instagram: '@tyra.decor',
  address: '128/18, Y-Block, Kidwai Nagar, Kanpur, U.P. – 208011, India',
  whatsapp: '917704007055',
};
